### ISSUE TITLE
Where is "ellipse" replacement?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stak#102]
I vaguely remember Ivo put a Python replacement of "ellipse" somewhere and was working on its notebook. Is it ready? Where is it?

Asking for Footprints Ticket 10432

**Comment by SaraOgaz** [comment]
It's going into photutils, Ivo's got a PR there now.  I was gonna wait until that was all in before closing this his PR here, but I guess there's no reason to wait... 

photutils: https://github.com/astropy/photutils/pull/532

**Comment by pllim** [comment]
Ah, okay. I'll pester Larry. Thanks!
