### ISSUE TITLE
Report constant-array FITS extensions generated by HSTCAL

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stak#103]
See astropy/astropy#6401 . @hcferguson said it should go here. Maybe @jamienoss can suggest some desired API options.

**Comment by nmiles2718** [comment]
@pllim  and @jamienoss, has there been any recent work done on this? I came across this same issue when reprocessing the darks for ACS/WFC. When CTE correcting an image, if the input BLV_TMP file has an extension with constant-arrays, then reading in that extension from the resulting BLC_TMP file yields NONE. I tested this by processing an image with the BIASCORR and BLEVCORR keywords set to PERFORM, then zero-ing out one of the DQ arrays in the BLV_TMP file produced and running it through CALACS with only the PCTECORR keyword set to PERFORM.

**Comment by pllim** [comment]
@nmiles2718 , I am a little confused as HSTIO that comes with HSTCAL knows how to read this format already. If you processed everything within HSTCAL, there should not be any problem. Can you please give some code to reproduce your problem above?

**Comment by nmiles2718** [comment]
Ahhh, I guess I was using CALACS and ACSCTE contained with acstools. Should I move my question there before continuing?

**Comment by pllim** [comment]
@nmiles2718 , yes please. Could be a bug in ACSTOOLS.

**Comment by SaOgaz** [comment]
This repo is being archived.  Project retired.
