### ISSUE TITLE
add initial notebook for noao.imred.crutil

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#18]
- `cosmicrays` - Remove cosmic rays using flux ratio algorithm
- `craverage` - Detect CRs against average and avoid objects
- `crcombine` - Combine multiple exposures to eliminate cosmic rays
- `credit` - Interactively edit cosmic rays using an image display
- `crfix` - Fix cosmic rays in images using cosmic ray masks
- `crgrow` - Grow cosmic rays in cosmic ray masks
- `crmedian` - Detect and replace cosmic rays with median filter
- `crnebula` - Detect and replace cosmic rays in nebular data
- `overview` - Overview of the package

**Comment by justincely** [comment]
Based on analysis of IRAF using code on github, this is one of the most used packages out there.  This should bump up in our priority list.

**Comment by SaraOgaz** [comment]
Whoops, just realized this is for all of noao.imred...
