### ISSUE TITLE
add notebook for fitsutil

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#21]
Fitsutil is largely a straight-forward package for manipulating FITS files, which looks like it can largely be accomplished through astropy.io.fits calls.

For example (Not complete listing):
fxconvert- Convert between IRAF image types.
fxcopy - Copy FITS files or FITS extension to an output FITS file
fxdelete - Delete FITS extensions in place fxextract- Extract a FITS extension
fxinsert - Insert FITS files or extensions into another MEF file
fxheader - List one line of header description per FITS unit
fxsplit - Split a multiple extension FITS file into single FITS files
fxdummyh - Create a dataless single FITS file
fxplf - Converts a pixel list file into a BINTABLE extension
fgwrite - Create a MEF file with FOREIGN extensions
fgread - Read a MEF file with FOREIGN extensions

**Comment by SaraOgaz** [comment]
I'm starting an outline of this notebook @jamienoss, but might not upload it for a while to the repo, FYI.

**Comment by SaraOgaz** [comment]
Have started a skeleton for this notebook, not yet pushed anywhere, just a local copy.

**Comment by SaraOgaz** [comment]
Closing, moved to: https://github.com/spacetelescope/stak-notebooks/issues/11
