### ISSUE TITLE
add notebook for images.imgeom

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#23]
Looks to be a mixture of transforms for images (and 1 for cubes).  

imgeom/:
 blkavg         im3dtran        imshift         magnify         shiftlines
 blkrep         imlintran       imtranspose     rotate

**Comment by SaraOgaz** [comment]
So @justincely,

all of these tasks have array manipulation equivalents, and I'm almost done with the notebook, but there's one hang up.  One task mentions WCS in such a way that it implies that this library is editing the WCS solution when it does the image manipulation.  Obviously, the scipy/numpy tasks don't know anything about WCS, so I'm not sure what we should do here.  I'm asking around to see if these kinds of tasks exist in drizzlepac as stand-alone tasks...  other then that the only possible equivalent I've found is stuff in Montage, but I haven't looked into that yet.

**Comment by SaraOgaz** [comment]
Okay, I found this for at least the rotation: http://docs.astropy.org/en/stable/modeling/
