### ISSUE TITLE
A few suggestions on the imfilter notebook

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/stak#30]
Took a quick look at the imfilter notebook. Very nice!

I have a few suggestions that might make the presentation clearer.

1. Using a random array for the "before convolution image" makes it a bit hard to see what the convolution is doing. I would suggest just putting a 1 at some pixel (say 4,4) and a 2 at another (say 6,6). This will make it much clearer that the convolution is smearing the image.

1. Use the viridis colormap or a greyscale. 

1. Delete the first example of convolving checkerboard kernel. Or move it later if you must keep it. I don't know of a use case for this kernel.

1. The notebook could be simplified if you skip the example of using scipy convolve, and just mention that it exists in the text. 

1. It might be helpful to plot your box and ring footprints after you create them.

1. I'm not sure what the motivation for fmedian and fmode were. Perhaps speed. I agree they seem like a corner case that were never much used.

1. Runmed also seems like a bit of a corner case. One could illustrate doing this by loading all the images into a cube and doing the running median that way. To implement a version that doesn't store all the data in memory is more complicated.

**Comment by justincely** [comment]
Thanks @hcferguson, @SaraOgaz is actually finishing up a re-implementation of the notebook layouts for these, which we expect to get merged in by the end-of-the week.  I'd appreciate another look at that once it's done for any further comments you have.

I don't think the changes address much of what you've brought up, since this change is unrelated to this issue, but i'd still be interested in your take on the new format.  We can follow up with these issues you brought up once this is merged.

**Comment by SaraOgaz** [comment]
@hcferguson,  I just finished replacing all the rand arrays with an image postcard for all the plots, and I think it looks much nicer (was Warren's suggestion), but I think it should accomplish the same goal as your suggestion.  

I will definitely be incorporating a lot of your other comments, thanks for the feedback!

For number 3, do you have any suggestion of a user provided kernel that someone might want?  I'd like to leave that example in there, but not sure what kind of custom kernels people use often.

**Comment by hcferguson** [comment]
Maybe use a Spitzer PSF? You can grab one from Karl Gordon's web page at  http://dirty.as.arizona.edu/~kgordon/mips/conv_psfs/conv_psfs.html.
