### ISSUE TITLE
add notebook for images.imcoords

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#31]
- `ccfind` - Find catalog sources in an image
- `ccget` - Extract objects from a text file catalog
- `ccmap` - Compute image plate solutions using matched coordinate lists
- `ccsetwcs` - Create an image celestial wcs from the ccmap plate solution
- `ccstd` - Transform to and from standard astrometric coordinates
- `cctran` - Transform coordinate lists using the ccmap plate solution
- `ccxymatch` - Match celestial and pixel coordinate lists
- `imcctran` - Transform image header from one celestial wcs to another
- `mkcwcs` - Make or update a simple celestial wcs
- `mkcwwcs` - Make or update a simple celestial/wavelength 3D wcs
- `skyctran` - Transform coordinates from one celestial wcs to another
- `starfind` - Automatically detect stellar objects in a list of images
- `wcsctran` - Transform coordinates from one iraf image wcs to another
- `wcsedit` - Edit an image wcs parameter
- `wcsreset` - Reset the specified image wcs

**Comment by SaraOgaz** [comment]
Closing, will eventually repost in stak-notebooks
