### ISSUE TITLE
add notebook for stsdas.analysis.statistics

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#37]
General statistics tasks, many I believe i've seen in scipy - but may need to actually create any that don't currently exist in the ecosystem.  

There's file I/O as well in many of the tasks, but that should be considered secondary to the algorithms themselves.

**Comment by SaraOgaz** [comment]
Skeleton notebook done, not yet pushed.

**Comment by SaraOgaz** [comment]
Closing, moved to: https://github.com/spacetelescope/stak-notebooks/issues/15
