### ISSUE TITLE
add notebook for stsdas.hst_calib.hstcos

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#38]
These are all python tasks anyway, so the notebook will just show the python way to call the same functions.  The notes at the top should clearly point to any CalCOS and COSTOOLS github repos and/or documentation.

- calcos
- splittag
- x1dcorr

**Comment by justincely** [comment]
Since I was on the team, I can do this one quickly.

**Comment by justincely** [comment]
I wrote a tutorial on splittag a while back: https://justincely.github.io/AAS224/splittag_tutorial.html

**Comment by SaraOgaz** [comment]
We've decided to just reference the documentation for the pipelines, but first ensuring their is enough documentation on said pipeline pages.

**Comment by SaraOgaz** [comment]
Moved to: https://github.com/spacetelescope/stak-notebooks/issues/16
