### ISSUE TITLE
add notebook for stsdas.toolbox.tools

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#39]
Ok, this one is a grab bag.  Creating strings and filennames from system date/time, precession, time conversion, redshifts, filepaths, converting numbers to different bases....

Effort for most should be low: time with datetime/astropy.time, filepaths with OS, base conversion can be done with python.  However, precession may take some time (i'm not very familiar with how difficult that is)

- `base2dec`:  Convert number in a base to decimal (base 10)
- `ddiff`: Find the differences between two directory trees.
- `dec2base`: Convert decimal number to another base
- `epoch`: Convert time between different formats.
- `fparse`: Parse a pathname specification into its component parts.
- `newredshift`: Artificially change the redshift of spectra.
- `tepoch`: Convert time between different formats in a table.
- `tprecess`: Precess images, tables, or lists of coordinates.
- `uniqfile`: Give a file a unique name.
- `uniqid`: Create a unique identifier from the current time.
- `uniqname`: Create a unique file name for files that are to be archived. 
- `uniqtab`: Give all the files in an STSDAS table unique names.

Not needed:
- `mkapropos`: Make the apropos database.

**Comment by justincely** [comment]
base conversion, while i found it:
-  http://stackoverflow.com/questions/8928240/convert-base-2-binary-number-string-to-int
-  http://stackoverflow.com/questions/699866/python-int-to-binary

**Comment by SaraOgaz** [comment]
Precession is in astropy. Skeleton notebook done, not yet pushed.

**Comment by SaraOgaz** [comment]
Moved to: https://github.com/spacetelescope/stak-notebooks/issues/17
