### ISSUE TITLE
add notebook for stsdas.toolbox.headers

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#40]
FITS header manipulation tasks. 

- `eheader`: Interactively edit an image header.
- `groupmod`: Add or delete group parameters in multi-group images.
- `hcheck`: Check image header keywords.
- `hdiff`: Display the differences between two image headers.
- `iminfo`: Print an instrument-specific header for a list of HST images, or a general header for a list of IRAF images.
- `stfhistory`: Read history information from a text file and add it to an image header.
- `upreffile`: Update calibration reference files names in image headers

**Comment by justincely** [comment]
eheader is interactive in IRAF.  This will need some discussion about whether we want to duplicate any interactive aspect of it.

Also, `hcheck` seems to be the same, or at least very similar, to hselect - which we already have a replacement for.

**Comment by SaraOgaz** [comment]
moved to: https://github.com/spacetelescope/stak-notebooks/issues/30
