### ISSUE TITLE
add notebook for stsdas.analysis.restore

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#44]
This package contains some complex algorithms and filters.  Some of these may exist in the scipy/numpy/scipy ecosystem, but I know for sure that some do not.  

- `adaptive` - Adaptive filter.
- `filterpars` - Pset for setting filter parameters used in the wiener task.
- `hfilter` - Adaptive low-pass filter based on H-transform.
- `lowpars` - Pset for setting the low-pass filter parameters used in the wiener task.
- `lucy` - Deconvolve an image using Leon Lucy's algorithm.
- `mem` - Deconvolve an image by the Maximum Entrophy Method (MEM)
- `modelpars` - Pset for setting model parameters used in the wiener task.
- `noisepars` - Pset for setting noise parameters used in the wiener task.
- `psfpars` - Pset for setting psf parameters used in the wiener task.
- `sclean` - Sigma-CLEAN deconvolution of 2-d images.
- `wiener` - Deconvolve a 2-dimensional image using a noniterative Fourier method.

**Comment by justincely** [comment]
lucy and weiner have implementations in http://scikit-image.org/docs/dev/api/skimage.restoration.html

**Comment by hcferguson** [comment]
@justincely I looked at the scikit-image versions a few sprints ago, and they didn't look easy to apply to astronomy images. Can't remember why. But your Lucy implementation was a better starting point.

**Comment by justincely** [comment]
Yeah i remember having some issues with the skimage one too, i think they do some min/max filtering on the data or something.  My `hfilter` from that sprint may be of use here too - but both will have to find their final place first.

**Comment by SaraOgaz** [comment]
Have notebook skeleton, haven't pushed yet.  Seems there's quite a few algorithms not currently in Python.

**Comment by SaraOgaz** [comment]
Closing call here, will reopen a new one eventally at https://github.com/spacetelescope/stak-notebooks/issues
