### ISSUE TITLE
add initial notebook for stsdas.analysis.isophote

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#48]
Elliptical isophote image analysis.

- bmodel
- controlpar
- ellipse
- geompar
- isoexam
- isoimap
- isomap
- isopall
- isoplot
- magpar
- map
- model
- samplepar

**Comment by hcferguson** [comment]
I don't believe this package has a wide user base. I'm not aware of a real equivalent in Python. Most people these days fit parametric models using GALFIT (not python) or several alternatives (a few in python, but I can't recall their names). I don't see much ellipse-fitting of isophotes these days. It's possible that people doing IFU surveys of early-type galaxies have developed some tools, but I didn't find any on a quick google search.

**Comment by SaraOgaz** [comment]
@larrybradley and @stscirij have both said that (at least in the case of ellipse) that this is still used quite a bit.  Good news is, Ivo Busko has already been developing the replacement in that we're working on reviewing.

**Comment by SaraOgaz** [comment]
Moved to: https://github.com/spacetelescope/stak-notebooks/issues/29
