### ISSUE TITLE
add initial notebook for stsdas.analysis.nebular

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#49]
Tasks for analyzing nebular emission lines

SSB has received helpdesk calls on this - check the helpdesk for current users and use-cases.  There is also a new package called [PyNeb](http://adsabs.harvard.edu/abs/2015A%26A...573A..42L) that may fill some of this need.  

Research needed on this topic.

**Comment by SaraOgaz** [comment]
PyNeb seems to cover all the IRAF tasks (was developed by same people). Skeleton notebooks is done, but not yet pushed.

**Comment by SaraOgaz** [comment]
moved to: https://github.com/spacetelescope/stak-notebooks/issues/25
