### ISSUE TITLE
pull out notebooks to separate repo?

### ISSUE THREAD

**Issue by justincely** [spacetelescope/stak#80]
Initially brought up by @jamienoss, it may make sense for the notebooks to be pulled out and hosted separately.  This would reduce the package dependency for STAK overall, as many of the notebooks may end up requiring esoteric packages that the rest of the codebase doesn't need.

This would also allow the notebooks to be easily hosted on services like [mybinder](http://mybinder.org/)

Posting this here so it's remembered for future discussion - does not need immediate addressing.

**Comment by justincely** [comment]
If this is done, the instructions can be updated to include the --recursive directive to clone: ` git clone --recursive` to pull submodules at the same time

**Comment by SaraOgaz** [comment]
Done, but not currently linking or submoduling...  new repo is https://github.com/spacetelescope/stak-notebooks
