### ISSUE TITLE
to-do for stsdas.toolbox.headers

### ISSUE THREAD

**Issue by SaraOgaz** [spacetelescope/stak#86]
eheader - do we want to replace this - GUI header editing?

upreffile - updates to latest reffiles, uses getref to grab "latest" calib files.  I think there's something that still does this in the cdbs software, ask Todd about it.

**Comment by SaraOgaz** [comment]
Talked to Larry about this, and input was that we don't want to worry about eheader (or any other GUI header/table editing tasks). Need to confirm.

**Comment by philhodge** [comment]
A GUI table editor is very useful!

**Comment by hbushouse** [comment]
Now that HST has switched from CDBS to CRDS I don't believe "upreffile" has any use or purpose. That was used to update the names of reference files in science product headers, so that the new ref files would get used when running the cal pipeline. Do the HST pipelines still get the names of ref files from the header or do they directly query CRDS (like the jwst pipeline) and let it find the right ref files on the fly?

**Comment by sosey** [comment]
They should all be getting the file names from the data headers

**Comment by hbushouse** [comment]
I still find myself using "eheader" fairly often. To me it's much quicker than doing endless calls to fits.setval() or editing the individual records in an HDU object, especially when you want to add new keywords and you want to put them in specific places. Sure, you can specify things like location in an argument to fits.setval(), but it's even faster yet for me to simply scroll to the place I want the new keyword and type it in.

**Comment by SaraOgaz** [comment]
As Megan said, yeah, still getting file names from the headers, so I do think documenting an "uprefheader" is worth doing.

**Comment by hcferguson** [comment]
Here is a script that spawns vi to edit a FITS header. I haven't figured out how to get something like this to work from within a Jupyter notebook, though.
```
# Simple eheader script using vi

from astropy.io import fits
import os
from subprocess import Popen

def eheader_file(infile,outfile,extension=0,tmpfile="~tmp_fits_header.txt"):
    hdulist = fits.open(infile)
    hdu = hdulist[extension]
    header = hdu.header
    hdu.header = eheader(hdu,tmpfile=tmpfile)
    if (outfile == infile):
       hdulist.writeto(outfile,clobber=True)
    else:
       hdulist.writeto(outfile)

def eheader(hdu,tmpfile="~tmp_fits_header.txt"):
    header = hdu.header
    header.totextfile(tmpfile,clobber=True)
    p = Popen("vi " + tmpfile, shell=True)
    pid, sts = os.waitpid(p.pid, 0)
    newheader = fits.header.Header.fromtextfile(tmpfile)
    os.remove(tmpfile)
    return new header
```

**Comment by SaraOgaz** [comment]
Moved: https://github.com/spacetelescope/stak-notebooks/issues/35
