### ISSUE TITLE
GUI tools

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stak#92]
Logging all GUI tools that we might want to replace.  The "how" is still undecided.  Possible options: ginga plug-ins, our write QT wrappers around astropy, ?

* eheader - interactive header editing (also covers tables.ttools.tupar)
* naoa.digiphot.daophot.pexamine - Interactively examine and edit a daophot database
* images.tv *might* have some stuff we need
* tables.ttools.tedit - interactive binTable editing
* stsdas.hst_calib.ctools.mkweight (?) - this one's a double whammy, spectra and GUI!
* stsdas.analysis.fitting (interactive fitting tools, I don't think we need this past what's already in imexam, but tasks are gfit1d,i2gaussfit,nfit1d,ngaussfit)

**Comment by sosey** [comment]
I'm still unclear why we wouldn't just use astropy tables and io.fits and show people how to open, edit, view and close them? It's fairly easy, for all these tasks. The gui wraps seems like extra work for not much gain and much more future maintenance (guis are expensive).

**Comment by philhodge** [comment]
On 04/26/2017 11:58 AM, Sara Ogaz wrote:
> tables.ttools.gtedit - interactive binTable editing

I would recommend tedit rather than gtedit.  gtedit is for editing a 
table based on what you see in an X vs Y plot, e.g. deleting outliers.  
tedit is for editing the table directly, e.g. adding or deleting a 
column, copy and paste a block of rows.

**Comment by philhodge** [comment]
Astropy tables probably lack some features that we have (and use) in 
ttools, but it makes sense to me to add those features to astropy 
tables, rather than to write independent gui tasks.  For almost all 
cases, I would rather have features available without having to use a gui.

**Comment by hcferguson** [comment]
There was something ridiculously convenient about being able to edit a FITS header in vi, which I think eheader let you do. I believe it left you on your own to try not to screw up the format, use the right number of characters or get the spelling right for keywords. Maybe it screamed if you tried to save and the header was no longer compliant. 

Anyway, I agree with Megan that we should resist developing a specialized GUI. Might make sense to think in terms of "translation tasks" that could allow users to use an existing widely supported tool to edit whatever it is they want to edit. 

For example, it might not be hard to support the functionality that eheader provided by writing a little task that would strip the header into an ASCII file and another that would check the header (edited with whatever tool the user liked) and replace the one that was there originally. This wouldn't be as slick as actually popping the editing window open for them, and wouldn't have the real-time validation and format-enforcement that you might build into a GUI. But it avoids having to develop the "editor" itself.

For Astropy tables, much as I hate Microsoft Excel, investing in better interoperability with that seems to me a better route than developing a custom GUI.

**Comment by SaraOgaz** [comment]
It's definitely not a decision we will be making lightly, and we're definitely planning on discussing it with DMSO and other parties first.  For now I'm just trying to keep track of ones we *might* want to worry about.

**Comment by SaOgaz** [comment]
This repo is being archived.  Project "retired".
