### ISSUE TITLE
ccdred replacement

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stak#98]
This is from FootPrints Ticket 10221: *I can not edit the ccdpr-parameters a simple example*
```python
$ python3
 Python 3.4.2 (default, Oct 8 2014, 10:45:20)
 [GCC 4.9.1] on linux
 Type "help", "copyright", "credits" or "license" for more information.
 >>> from pyraf import iraf
 Warning: sscanf library not installed on linux
 >>> iraf.mscred(_doprint=0)
 This is the initial release of the IRAF FITSUTIL package
 to include support for FITS tile compression via 'fpack'.
 Please send comments and questions to seaman@noao.edu.
 >>> iraf.lparam(iraf.ccdpr)
       ...clip clip clip....
   (overscan = yes) Apply overscan strip correction?
        (trim = yes) Trim the image?
     (zerocor = yes) Apply zero level correction?
      ...clip clip clip....
 >>> iraf.ccdpr.setParam("trim", 'no')
 >>> iraf.lparam(iraf.ccdpr)
       ...clip clip clip....
   (overscan = yes) Apply overscan strip correction?
        (trim = yes) Trim the image?
     (zerocor = yes) Apply zero level correction?
      ...clip clip clip....
```
*The intermittent part is that when I do this using my desktop*
```python
 $ python3
 Python 3.4.3 (default, Nov 17 2016, 01:08:31)
 [GCC 4.8.4] on linux
 Type "help", "copyright", "credits" or "license" for more information.
 >>> from pyraf import iraf
    ...clip clip clip....
 the parameters are updated as expected. 
```
*I'm planning to use pyraf/ccdred in a postprocessing task for the telescope data, so using my desktop is not an option or workaround.*

*About the "ccdproc/python"-version. I have not found any statement that the python version would work smoothly with mosaics (to be honest I have not tried either). I think using "mscred/ccdred" is muuuuch more convenient to use than the "old noao/imred...".*

*I think my "problem" is that I have used iraf a long time and I like just typing on the command line, instead of clicking here and there. So reducing one night imaging data is very straight forward, few
commands always very similar. Also for quick look iraf + ds9 is fast and easy (as I know the commands).*

*Also one very nice feature is the iraf log-file, i.e. all command line stuff is there with a time stamp, so I can use it as my documentation/archive.*

**Comment by SaOgaz** [comment]
Archiving Repo.
